### PR TITLE
fix call breaks

### LINKED ISSUE #228: [Bug]: `eval_code` splits code at the wrong position
<details>
<summary>vitals app</summary>

```r
pkgload::load_all("teal.code")
library(teal.modules.clinical)
library(teal.modules.general)
options(shiny.useragg = FALSE)

## Data reproducible code ----
data <- teal_data()
data <- within(data, {
  library(random.cdisc.data)
  library(nestcolor)

  ADSL <- radsl(seed = 1)
  ADMH <- radmh(ADSL, seed = 1)
  ADAE <- radae(ADSL, seed = 1)
  ADCM <- radcm(ADSL, seed = 1)
  ADVS <- radvs(ADSL, seed = 1)
  ADLB <- radlb(ADSL, seed = 1)

  ## Modify ADCM
  ADCM$CMINDC <- paste0("Indication_", as.numeric(ADCM$CMDECOD))
  ADCM$CMDOSE <- 1
  ADCM$CMTRT <- ADCM$CMCAT
  ADCM$CMDOSU <- "U"
  ADCM$CMROUTE <- "CMROUTE"
  ADCM$CMDOSFRQ <- "CMDOSFRQ"
  ADCM$CMASTDTM <- ADCM$ASTDTM
  ADCM$CMAENDTM <- ADCM$AENDTM

  teal.data::col_labels(
    ADCM[c("CMINDC", "CMTRT", "ASTDY", "AENDY")]
  ) <- c(
    "Indication",
    "Reported Name of Drug, Med, or Therapy",
    "Study Day of Start of Medication",
    "Study Day of End of Medication"
  )

  ## Modify ADHM
  ADMH[["MHDISTAT"]] <- "ONGOING"
  teal.data::col_labels(ADMH[c("MHDISTAT")]) <- c("Status of Disease")
})

join_keys(data) <- default_cdisc_join_keys[c("ADSL", "ADMH", "ADAE", "ADCM", "ADVS", "ADLB")]

## App configuration ----
ADSL <- data[["ADSL"]]
ADMH <- data[["ADMH"]]
ADAE <- data[["ADAE"]]
ADCM <- data[["ADCM"]]
ADVS <- data[["ADVS"]]
ADLB <- data[["ADLB"]]


## Define variable inputs
aeterm_input <- choices_selected(
  choices = variable_choices(ADAE, "AETERM"),
  selected = "AETERM"
)

cmtrt_input <- choices_selected(
  choices = variable_choices(ADCM, "CMTRT"),
  selected = "CMTRT"
)

cmindc_input <- choices_selected(
  choices = variable_choices(ADCM, "CMINDC"),
  selected = "CMINDC"
)

atirel_input <- choices_selected(
  choices = variable_choices(ADCM, "ATIREL"),
  selected = "ATIREL"
)

cmdecod_input <- choices_selected(
  choices = variable_choices(ADCM, "CMDECOD"),
  selected = "CMDECOD"
)

## App header and footer ----
nest_logo <- "https://raw.githubusercontent.com/insightsengineering/hex-stickers/main/PNG/nest.png"
app_source <- "https://github.com/insightsengineering/teal.gallery/tree/main/patient-profile"
gh_issues_page <- "https://github.com/insightsengineering/teal.gallery/issues"

header <- tags$span(
  style = "display: flex; align-items: center; justify-content: space-between; margin: 10px 0 10px 0;",
  tags$span("My first teal app", style = "font-size: 30px;"),
  tags$span(
    style = "display: flex; align-items: center;",
    tags$img(src = nest_logo, alt = "NEST logo", height = "45px", style = "margin-right:10px;"),
    tags$span(style = "font-size: 24px;", "NEST @ Roche")
  )
)

footer <- tags$p(
  "This teal app is brought to you by the NEST Team at Roche/Genentech.
        For more information, please visit:",
  tags$a(href = app_source, target = "_blank", "Source Code"), ", ",
  tags$a(href = gh_issues_page, target = "_blank", "Report Issues")
)

app <- init(
  data = data,
  title = build_app_title("Patient Profile Analysis Teal Demo App", nest_logo),
  header = header,
  footer = footer,
  filter = teal_slices(
    count_type = "all",
    teal_slice(dataname = "ADSL", varname = "SEX"),
    teal_slice(dataname = "ADSL", varname = "AGE")
  ),
  modules = modules(
    tm_g_pp_vitals(
      label = "Vitals",
      parentname = "ADSL",
      patient_col = "USUBJID",
      plot_height = c(600L, 200L, 2000L),
      paramcd = choices_selected(
        choices = variable_choices(ADVS, "PARAMCD"),
        selected = "PARAMCD"
      ),
      xaxis = choices_selected(
        choices = variable_choices(ADVS, "ADY"),
        selected = "ADY"
      ),
      aval_var = choices_selected(
        choices = variable_choices(ADVS, "AVAL"),
        selected = "AVAL"
      )
    )
  )
)

shinyApp(app$ui, app$server)
```

</details>

Above app fails as split_code wrongly detects end of the call and results in evaluation error:


<img width="807" alt="Skärmavbild 2024-11-12 kl  09 07 17" src="https://github.com/user-attachments/assets/c4e96c2c-53a5-424e-95d1-45640dabfe08">

Look, above call has been splitted into following:

```
# [15] "base_labels <- stats::setNames(c(\"140mmHg\", \"90mmHg\", \"38° C\", \"20/min\", \"94%\", \"100bpm\"),  known_vita)\np"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
# [16] "aramcd_labels_e <- base_labels[paramcd_levels_e]\n"    
```

### PR DESCRIPTION
**Pull request by gogonzo**
closes #228 

Core issue is that `split_code` interprets data from `parseData` which returns exact index of the end of the call. Based on the information of the call-break, we decided also to associate a call-terminator to the current call. For example, if call ends at line: 1 and col: 7 (`a <- 11` has 7 characters) we can also add `\n` to this call by changing index to line: 1; col: 7 + 2. This is how we do it on main. Thanks to this we keep exact formatting in `@code` slot and we are sure that `eval_code` and `get_code` would return the same result.

```r
# this call
a <- 11\nb <- 2

# turns into
c(
  "a <- 11\n",
  "b <- 2"
)
```

Problem arises with `;` as it is not a two character element, and indexing could cause a failure. In the `split_code/get_code` we somehow managed this by adding some extra "cleaners" and still keep the eval_code-get_code consistent somehow. 
However,  `tm_g_pp_vitals` module does something nasty. Module produces very long call and deparse must have done something not easy to handle by `split_code`. See the #228 to see how `split_call` fails. 

**Solution:** Because end of the call is detected properly and sometimes there is a problem with detecting where the next call begins, I decided to start the next call at the end of the previous and remove `;` or `\n` from the beginning. This solution results in `@code` to not store call terminators and `get_code` combines calls by `\n`. In other words `;` is converted into `\n` always.

### CODE REVIEW

File: R/utils-get_code_dependency.R [hunk 1]
```diff
@@ -467,16 +467,15 @@ split_code <- function(code) {
 
   idx_start <- c(
     0, # first call starts in the beginning of src
-    char_count_lines[call_breaks[, "line"]] + call_breaks[, "col"] + 2
+    char_count_lines[call_breaks[, "line"]] + call_breaks[, "col"] + 1
```
Comment (gogonzo) [inline R/utils-get_code_dependency.R:470]: next call starts after call ends - most probably next one starts with  `\n` or `;` - see line 480

**Comment by m7pr** [comment]
Thanks for writing an extensive PR description. Very useful for people reviewing it. 

> In other words ; is converted into \n always.

Not a big deal in the end. I remember how many things you needed to deal with to get the parser to work and keep the code as-is. The current state on this PR is still better than what we had on main before last Friday, so this is still a huge improvement.

Will review on my own today

File: R/qenv-get_code.R [hunk 2]
```diff
@@ -141,7 +141,7 @@ setMethod("get_code", signature = "qenv", function(object, deparse = TRUE, names
   }
 
   if (deparse) {
-    gsub(";\n", ";", paste(gsub("\n$", "", unlist(code)), collapse = "\n"))
+    paste(unlist(code), collapse = "\n")
```
Comment (m7pr) [inline R/qenv-get_code.R:144]: This is great improvement

File: R/utils-get_code_dependency.R [hunk 3]
```diff
@@ -467,16 +467,15 @@ split_code <- function(code) {
...
     nchar(code) # last call end in the end of src
   )
   new_code <- substring(code, idx_start, idx_end)
 
-  # we need to remove leading semicolons from the calls and move them to the previous call
-  #  this is a reasult of a wrong split, which ends on the end of call and not on the ;
-  #  semicolon is treated by R parser as a separate call.
-  gsub("^([[:space:]])*;(.+)$", "\\1\\2", new_code, perl = TRUE)
+  # line split happens before call terminator (it could be `;` or `\n`) and the terminator goes to the next line
+  # we need to move remove leading and add \n instead when combining calls
```
Comment (m7pr) [inline R/utils-get_code_dependency.R:479]: ? I'm trying to make sense out of this line
however the `gsub` actually removes `;` and `\n` and there is no substitution
```suggestion
  # we need to remove leading `;` and add `\n` instead when combining calls
```

File: tests/testthat/test-qenv_get_code.R [hunk 4]
```diff
@@ -58,7 +58,7 @@ testthat::test_that("get_code returns code with comments and empty spaces", {
     # closing comment
     "
   q <- eval_code(qenv(), code)
-  testthat::expect_equal(get_code(q), code)
+  testthat::expect_equal(get_code(q), gsub(";", "\n", code))
```
Comment (m7pr) [inline tests/testthat/test-qenv_get_code.R:61]: When you run

```r
code <- "
    # header comment after white space
    a <- 1L; b <- 2 #inline comment
    c <- 3
    # closing comment
    "
q <- eval_code(qenv(), code)
cat(get_code(q))

```

You can see that indentation for `b` is different than the rest of the code

```r

    # header comment after white space
    a <- 1L
 b <- 2 #inline comment
    c <- 3
    # closing comment
    
```

Should we substitute `;` with `\n` but prefixed with the number of whitespaces that existed at the beginning of the line in which `;` appeared? So that the call looks like this

```r

    # header comment after white space
    a <- 1L
    b <- 2 #inline comment
    c <- 3
    # closing comment
    
```

**Comment by m7pr** [comment]
Hey @gogonzo this is great! I left one comment that I think is within our reach 
https://github.com/insightsengineering/teal.code/pull/229#discussion_r1839745089

File: tests/testthat/test-qenv_get_code.R (hunk 4 above)
Comment (gogonzo) [reply tests/testthat/test-qenv_get_code.R:61]: How can you determine the indent here? Previous of `b` is `\n    # header comment after white space\n    a <- 1L`. Here we would need to:
```
call_previous_lines <- split(call[i-1], "\n")
previous_line <- call_previous_lines[length(call_previous_lines)]
previous_line_indent <- gsub("^([\t ]*).*", "\\1", previous_line)
# here we need also to substract one space as 'b' call starts with a single space
paste0(previous_line_indent, call[i])
```

But it doesn't solve all the problems. Because when one wants to pull only the code of `b`, then it would have a indent given by previous (possibly unrelated line).

Comment (m7pr) [reply tests/testthat/test-qenv_get_code.R:61]: Thanks for looking into that and for the explanation.
Not ideal but I think we can live with those limitations : )

So this is ready to be merged

**Review by m7pr — APPROVED** [review]
